# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T14:21:04+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class AtAltTemp(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class ExosphericTemp(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class TotalMassDensity(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class Jb2008GetResponse(BaseModel):
    at_alt_temp: Optional[AtAltTemp] = None
    exospheric_temp: Optional[ExosphericTemp] = None
    total_mass_density: Optional[TotalMassDensity] = None


class ArDensity(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class HDensity(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class HeDensity(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class N2Density(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class NDensity(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class O2Density(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class ODensity(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class AnomalousODensity(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class Ap(BaseModel):
    value: Optional[float] = None


class F107(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class F107a(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class Nrlmsise00GetResponse(BaseModel):
    Ar_density: Optional[ArDensity] = None
    H_density: Optional[HDensity] = None
    He_density: Optional[HeDensity] = None
    N2_density: Optional[N2Density] = None
    N_density: Optional[NDensity] = None
    O2_density: Optional[O2Density] = None
    O_density: Optional[ODensity] = None
    anomalous_O_density: Optional[AnomalousODensity] = None
    ap: Optional[Ap] = None
    at_alt_temp: Optional[AtAltTemp] = None
    exospheric_temp: Optional[ExosphericTemp] = None
    f107: Optional[F107] = None
    f107a: Optional[F107a] = None
    total_mass_density: Optional[TotalMassDensity] = None


class EastwardWindNeutral(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class NorthwardWindNeutral(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class Point(BaseModel):
    altitude: Optional[float] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None


class TempNeutral(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class UpwardWindNeutral(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class WamIpeGetResponse(BaseModel):
    N2_density: Optional[N2Density] = Field(
        None, description='Molecular nitrogen density in (/m3).\n'
    )
    O2_density: Optional[O2Density] = Field(
        None, description='Moleculary oxygen density in (/m3).\n'
    )
    O_density: Optional[ODensity] = Field(
        None, description='Oxygen atomic density in (/m3).\n'
    )
    eastward_wind_neutral: Optional[EastwardWindNeutral] = Field(
        None, description='Easterly component of neutral wind velocity in (m/s).\n'
    )
    northward_wind_neutral: Optional[NorthwardWindNeutral] = Field(
        None, description='Northerly component of neutral wind velocity in (m/s).\n'
    )
    point: Optional[Point] = Field(None, description='The given point in the request.')
    temp_neutral: Optional[TempNeutral] = Field(
        None, description='Temperature of the atmosphere in (K).\n'
    )
    total_mass_density: Optional[TotalMassDensity] = Field(
        None, description='Total mass density (kg/m3).\n'
    )
    upward_wind_neutral: Optional[UpwardWindNeutral] = Field(
        None, description='Upward component of neutral wind velocity in (m/s).\n'
    )
